### ISSUE TITLE
Default FirebaseApp is not initialized in this process

### ISSUE THREAD

**Issue by yuriploc** [chemerisuk/cordova-plugin-firebase-hooks#3]
This is probably related to #2.

When I run
```javascript
window.cordova.plugins.firebase.crash.report("Firebase Crash Report");
```

I get the following exception in `logcat`:

```
E PluginManager: Uncaught exception from plugin
E PluginManager: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.myapp. Make sure to call FirebaseApp.initializeApp(Context) first.
E PluginManager: 	at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
E PluginManager: 	at com.google.firebase.crash.FirebaseCrash.zzWu(Unknown Source)
E PluginManager: 	at com.google.firebase.crash.FirebaseCrash.log(Unknown Source)
E PluginManager: 	at by.chemerisuk.cordova.firebase.FirebaseCrashPlugin.report(FirebaseCrashPlugin.java:26)
E PluginManager: 	at by.chemerisuk.cordova.firebase.FirebaseCrashPlugin.execute(FirebaseCrashPlugin.java:17)
E PluginManager: 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
E PluginManager: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
E PluginManager: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
E PluginManager: 	at org.crosswalk.engine.XWalkExposedJsApi.exec(XWalkExposedJsApi.java:40)
E PluginManager: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
E PluginManager: 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
E PluginManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E PluginManager: 	at android.os.Looper.loop(Looper.java:148)
E PluginManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by chemerisuk** [comment]
This plugin is no longer maintained. All cordova firebase plugins are depended on cordova-plugin-firebase-analytics.
